### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by limafresh** [iTroy0/WebP-Converter#1]
I am the first one who tried your project.
1. Remove winsound so that the project can work on Linux, not just Windows. I removed it - the application starts. After all, winsound is a library created only for Windows.
2. The created video is corrupted and the video player gives an error - it needs to be fixed.
3. Not everything fits in the window, especially after opening webp and creating a preview. Put it in CTkScrollableFrame.

**Comment by iTroy0** [comment]
thats was quick !
1.im gonna remove winsound as its not necessary after all.
2.i havent tried this on linux i just tried it on windows.
3.im not sure what you mean. can you please post a screenshot or explain more

**Comment by limafresh** [comment]
3. 

![Image](https://github.com/user-attachments/assets/3d141bf2-4c31-4c74-99b7-7711fd0b33da)

Doesn't fit in the window. But CustomTkinter has such a widget - it's called CTkScrollableFrame, and it has a built-in scrollbar, so if it doesn't fit, you can scroll.

**Comment by iTroy0** [comment]
> ![Image](https://github.com/user-attachments/assets/3d141bf2-4c31-4c74-99b7-7711fd0b33da)
> 
> Doesn't fit in the window. But CustomTkinter has such a widget - it's called CTkScrollableFrame, and it has a built-in scrollbar, so if it doesn't fit, you can scroll.

i have updated the code with CTkScrollableFrame and added new features 

1. Scrollable Main Frame
a.The whole UI inside a CTkScrollableFrame
b.Smooth scroll up/down when content is larger

2. Animated Preview for Selected WebP
a.Preview plays frames of the selected WebP
b.Loops automatically
c.Shows "first frame" immediately after selection

3. Pause and Resume Preview Animation
a.Hover over preview → animation pauses
b.Mouse leave → animation resumes playing

4. Select Multiple WebP Files
a.Choose WebP File(s) button supports multi-file selection
b.Displays all selected files in a scrollable list

5. Clickable File List for Quick Preview
a.You can click any file from the list to instantly update the preview
b.File names nicely listed, with remove ❌ button next to each file

**Comment by limafresh** [comment]
Yes, it got better, and winsound was removed, thanks to which the project runs on Linux without deleting lines, but the application still does not cope well with its task - it converts only to webm, and in mp4 and mkv - it creates damaged videos of 0 B in size.

**Comment by iTroy0** [comment]
> Yes, it got better, and winsound was removed, thanks to which the project runs on Linux without deleting lines, but the application still does not cope well with its task - it converts only to webm, and in mp4 and mkv - it creates damaged videos of 0 B in size.

i have just tested the application on WSL Ubuntu 24.04.1 LTS [Linux Test](https://i.ibb.co/SD1FrxYT/image.png)
its fully working. do you mind posting your console if you have any errors.

also please try this 
1.save this as start.sh inside your WebP-Converter Folder.

```bash
#!/bin/bash

echo "🚀 Starting Build Process for WebP Converter..."

# 1. Ensure python3-tk is installed
echo "🔍 Checking for tkinter support..."
if ! python3 -c "import tkinter" &> /dev/null; then
    echo "⚙️ Installing tkinter (requires sudo)..."
    sudo apt update
    sudo apt install -y python3-tk
else
    echo "✅ Tkinter already installed!"
fi

# 2. Create virtual environment if missing
if [ ! -d ".venv" ]; then
    echo "📦 Creating virtual environment (.venv)..."
    python3 -m venv .venv
fi

# 3. Activate virtual environment
echo "🔋 Activating virtual environment..."
source .venv/bin/activate

# 4. Install requirements
echo "📚 Installing Python packages..."
pip install --upgrade pip
pip install -r requirements.txt

# 5. Run your script directly 
echo "🚀 Launching WebP Converter app..."
python3 webp_converter_gui.py

# 6. Deactivate virtual environment after exit
deactivate
```
2.Make it executable:

```bash
chmod +x build.sh
```

3.Run it
```bash
./start.sh
```

**Comment by limafresh** [comment]
> > Yes, it got better, and winsound was removed, thanks to which the project runs on Linux without deleting lines, but the application still does not cope well with its task - it converts only to webm, and in mp4 and mkv - it creates damaged videos of 0 B in size.
> 
> i have just tested the application on WSL Ubuntu 24.04.1 LTS [Linux Test](https://i.ibb.co/SD1FrxYT/image.png) its fully working. do you mind posting your console if you have any errors.
> 
> also please try this 1.save this as start.sh inside your WebP-Converter Folder.
> 
> #!/bin/bash
> 
> echo "🚀 Starting Build Process for WebP Converter..."
> 
> # 1. Ensure python3-tk is installed
> echo "🔍 Checking for tkinter support..."
> if ! python3 -c "import tkinter" &> /dev/null; then
>     echo "⚙️ Installing tkinter (requires sudo)..."
>     sudo apt update
>     sudo apt install -y python3-tk
> else
>     echo "✅ Tkinter already installed!"
> fi
> 
> # 2. Create virtual environment if missing
> if [ ! -d ".venv" ]; then
>     echo "📦 Creating virtual environment (.venv)..."
>     python3 -m venv .venv
> fi
> 
> # 3. Activate virtual environment
> echo "🔋 Activating virtual environment..."
> source .venv/bin/activate
> 
> # 4. Install requirements
> echo "📚 Installing Python packages..."
> pip install --upgrade pip
> pip install -r requirements.txt
> 
> # 5. Run your script directly 
> echo "🚀 Launching WebP Converter app..."
> python3 webp_converter_gui.py
> 
> # 6. Deactivate virtual environment after exit
> deactivate
> 2.Make it executable:
> 
> chmod +x build.sh
> 3.Run it
> 
> ./start.sh

There are no errors in the console, but it creates corrupted videos of 0 bytes if you select the mp4 or mkv format

**Comment by iTroy0** [comment]
> > > Yes, it got better, and winsound was removed, thanks to which the project runs on Linux without deleting lines, but the application still does not cope well with its task - it converts only to webm, and in mp4 and mkv - it creates damaged videos of 0 B in size.
> > 
> > 
> > i have just tested the application on WSL Ubuntu 24.04.1 LTS [Linux Test](https://i.ibb.co/SD1FrxYT/image.png) its fully working. do you mind posting your console if you have any errors.
> > also please try this 1.save this as start.sh inside your WebP-Converter Folder.
> > #!/bin/bash
> > echo "🚀 Starting Build Process for WebP Converter..."
> > # 1. Ensure python3-tk is installed
> > echo "🔍 Checking for tkinter support..."
> > if ! python3 -c "import tkinter" &> /dev/null; then
> > echo "⚙️ Installing tkinter (requires sudo)..."
> > sudo apt update
> > sudo apt install -y python3-tk
> > else
> > echo "✅ Tkinter already installed!"
> > fi
> > # 2. Create virtual environment if missing
> > if [ ! -d ".venv" ]; then
> > echo "📦 Creating virtual environment (.venv)..."
> > python3 -m venv .venv
> > fi
> > # 3. Activate virtual environment
> > echo "🔋 Activating virtual environment..."
> > source .venv/bin/activate
> > # 4. Install requirements
> > echo "📚 Installing Python packages..."
> > pip install --upgrade pip
> > pip install -r requirements.txt
> > # 5. Run your script directly
> > echo "🚀 Launching WebP Converter app..."
> > python3 webp_converter_gui.py
> > # 6. Deactivate virtual environment after exit
> > deactivate
> > 2.Make it executable:
> > chmod +x build.sh
> > 3.Run it
> > ./start.sh
> 
> There are no errors in the console, but it creates corrupted videos of 0 bytes if you select the mp4 or mkv format

not sure how i can help then, would like me to build it for you and try?
